name: 'Build AUR Package'
description: 'Test build an AUR package in Docker container'
inputs:
  repo-name:
    description: 'AUR repository name to build'
    required: true
    default: 'qv2ray-dev-git'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
