name: 'Add Repo Package For Archlinux'
description: 'Test add an AUR package in Docker container'
inputs:
  repo-name:
    description: 'repository name'
    required: true
    default: '135e2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo-name }}
